spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never

pelicula:
  service:
    url: ${PELICULA_SERVICE_URL:http://localhost:8081/api/v1/peliculas}

server:
  port: ${PORT:8080}

logging:
  level:
    evaluacion3.valoracion: WARN
