spring:
  cloud:
    gateway:
      routes:
        - id: pelicula-microservicio
          uri: ${PELICULA_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/peliculas/**
        - id: genero-microservicio
          uri: ${GENERO_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/generos/**
        - id: valoracion-microservicio
          uri: ${VALORACION_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/valoraciones/**
        - id: usuario-microservicio
          uri: ${USUARIO_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/usuarios/**

logging:
  level:
    org.springframework.cloud.gateway: WARN

server:
  port: ${PORT:8080}
