spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

logging:
  level:
    evaluacion3.subscription: DEBUG
